--- 
title: "Detrendr ImageJ Plugin Tutorial"
author: "Rory Nolan"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [book.bib, packages.bib, papers.bib, theses.bib]
biblio-style: apalike
link-citations: yes
github-repo: rorynolan/ij_detrendr
description: "A tutorial on the Detrendr ImageJ plugin"
---

```{r load-pkgs, include=FALSE}
# The dev version of latex2exp is needed
pacman::p_load(tidyverse, bookdown, knitr)

opts_chunk$set(comment = "#>", fig.asp = 0.6, 
               out.width = "100%", fig.align = "left",
               message = FALSE, warning = FALSE)
```

# Introduction {-#intro}

This is a tutorial on the _Detrendr_ plugin for _ImageJ_ [@ImageJ]. This plugin implements _Robin Hood_ detrending. For now, the only place you can read about this is in my thesis [@MyThesis], but work is underway on a paper about this. So for now, if you want to learn about the _Robin Hood_ algorithm, go there. This tutorial is about teaching you how to use the _ImageJ_ implementation of the algorithm, it's not intended to teach you how the algorithm itself works.

For those of you who aren't in love with graphical interfaces, this algorithm is also available as the R package `detrendr` which is on [CRAN](https://cran.r-project.org/package=detrendr) and is described in detail at https://rorynolan.github.io/detrendr/.

This book is divided into two chapters: one detailing how to install the plugin and the next showing how to use it. They can be accessed from the left pane of this website.

